2019/09/25 11:01:05 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.6:9001", host: "symfony.localhost"
2019/09/25 11:01:05 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 11:01:10 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.6:9001", host: "symfony.localhost"
2019/09/25 11:01:10 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 11:20:38 [error] 6#6: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.6:9001", host: "symfony.localhost"
2019/09/25 11:20:39 [error] 6#6: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.22.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 11:20:40 [error] 6#6: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.6:9001", host: "symfony.localhost"
2019/09/25 11:20:40 [error] 6#6: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.22.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 11:20:41 [error] 6#6: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.6:9001", host: "symfony.localhost"
2019/09/25 11:20:41 [error] 6#6: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.22.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 11:24:58 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.6:9001", host: "symfony.localhost"
2019/09/25 11:24:59 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.23.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 11:25:00 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.6:9001", host: "symfony.localhost"
2019/09/25 11:25:00 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.23.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 11:26:14 [error] 7#7: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.6:9001", host: "symfony.localhost"
2019/09/25 11:26:14 [error] 7#7: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.23.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 11:32:10 [error] 7#7: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.6:9001", host: "symfony.localhost"
2019/09/25 11:32:10 [error] 7#7: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.23.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 11:36:35 [error] 10#10: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.24.0.6:9001", host: "symfony.localhost"
2019/09/25 11:36:36 [error] 10#10: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.24.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 11:36:37 [error] 10#10: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.24.0.6:9001", host: "symfony.localhost"
2019/09/25 11:36:37 [error] 10#10: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.24.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 11:36:37 [error] 10#10: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.24.0.6:9001", host: "symfony.localhost"
2019/09/25 11:36:37 [error] 10#10: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.24.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 11:36:37 [error] 10#10: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.24.0.6:9001", host: "symfony.localhost"
2019/09/25 11:36:37 [error] 10#10: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.24.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 11:36:37 [error] 10#10: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.24.0.6:9001", host: "symfony.localhost"
2019/09/25 11:36:37 [error] 10#10: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.24.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 11:41:12 [error] 10#10: *18 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.24.0.6:9001", host: "symfony.localhost"
2019/09/25 11:41:12 [error] 10#10: *18 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.24.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:01:03 [error] 6#6: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.6:9001", host: "symfony.localhost"
2019/09/25 14:01:03 [error] 6#6: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.26.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:09:29 [error] 33#33: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.6:9001", host: "symfony.localhost"
2019/09/25 14:09:30 [error] 33#33: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.26.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:09:40 [error] 33#33: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.6:9001", host: "localhost"
2019/09/25 14:09:42 [error] 33#33: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.6:9001", host: "localhost"
2019/09/25 14:15:29 [error] 6#6: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.28.0.6:9001", host: "symfony.localhost"
2019/09/25 14:15:30 [error] 6#6: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.28.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:15:30 [error] 6#6: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.28.0.6:9001", host: "symfony.localhost"
2019/09/25 14:15:31 [error] 6#6: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.28.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:15:31 [error] 6#6: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.28.0.6:9001", host: "symfony.localhost"
2019/09/25 14:15:31 [error] 6#6: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.28.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:18:34 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.29.0.6:9001", host: "symfony.localhost"
2019/09/25 14:18:34 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.29.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:18:35 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.29.0.6:9001", host: "symfony.localhost"
2019/09/25 14:18:35 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.29.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:18:42 [error] 7#7: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.29.0.6:9001", host: "localhost"
2019/09/25 14:19:38 [error] 7#7: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.29.0.6:9001", host: "symfony.localhost"
2019/09/25 14:19:38 [error] 7#7: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.29.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:19:41 [error] 7#7: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.29.0.6:9001", host: "symfony.localhost"
2019/09/25 14:19:41 [error] 7#7: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.29.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:31:58 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.6:9001", host: "symfony.localhost"
2019/09/25 14:31:58 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.30.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:31:59 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.6:9001", host: "symfony.localhost"
2019/09/25 14:31:59 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.30.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:31:59 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.6:9001", host: "symfony.localhost"
2019/09/25 14:31:59 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.30.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:31:59 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.6:9001", host: "symfony.localhost"
2019/09/25 14:31:59 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.30.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:31:59 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.6:9001", host: "symfony.localhost"
2019/09/25 14:32:00 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.30.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:32:00 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.6:9001", host: "symfony.localhost"
2019/09/25 14:32:00 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.30.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:32:00 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.6:9001", host: "symfony.localhost"
2019/09/25 14:32:00 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.30.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:32:01 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.6:9001", host: "symfony.localhost"
2019/09/25 14:32:01 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.30.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:32:01 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.6:9001", host: "symfony.localhost"
2019/09/25 14:32:01 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.30.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:32:01 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.6:9001", host: "symfony.localhost"
2019/09/25 14:32:01 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.30.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:36:01 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.6:9001", host: "symfony.localhost"
2019/09/25 14:36:01 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.31.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:36:02 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.6:9001", host: "symfony.localhost"
2019/09/25 14:36:02 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.31.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:36:02 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.6:9001", host: "symfony.localhost"
2019/09/25 14:36:03 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.31.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2019/09/25 14:41:10 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.0.6:9001", host: "symfony.localhost"
2019/09/25 14:41:10 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.0.6:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
